apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: 13.235.74.86:30578/hello-world:latest   # Nexus registry image
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

