apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  labels:
    app: hello-world
spec:
  selector:
    app: hello-world
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080   # choose any free NodePort (between 30000–32767)

